config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'

  resources :categories do
    resources :images do
      resources :similar_images
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :images, dependent: :destroy

  validates :title, presence: true, length: {in: 3..20 }
end

app/models/concerns/SimilarImageValidator.rb
class SimilarImageValidator < ActiveModel::Validator
  def validate(record)
    if record.image? then
      @image = Image.find(record.image_id)
      @width = @image.image.width
      @max_width = @width + @width * 0.1
      @min_width = @width - @width * 0.1

      @height = @image.image.height
      @max_height = @height + @height * 0.1
      @min_height = @height - @height * 0.1

      @format = @image.image.content_type

      if (record.image.width > @max_width || record.image.width < @min_width) then
        record.errors.add(:image, "width must be between #{@min_width} and #{@max_width} but was #{record.image.width}")
      end

      if (record.image.height > @max_height || record.image.height < @min_height) then
        record.errors.add(:image, "width must be between #{@min_height} and #{@max_height} but was #{record.image.height}")
      end

      unless (record.image.content_type == @format) then
        record.errors.add(:image, "must be #{@format} but was #{record.image.content_type}")
      end
    else
      record.errors.add(:image, "can't be blank")
    end

  end
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :category
  has_many :similar_images, dependent: :destroy

  validates :title, presence: true, length: {in: 3..20 }
  validates :image, presence: true
end

app/models/similar_image.rb
class SimilarImage < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :image

  validates :title, presence: true, length: {in: 3..20 }
  validates :image, presence: true

  validates_with SimilarImageValidator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:title)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    redirect_to new_category_image_path
  end

  def new
    @category = Category.find(params[:category_id])
    @image = @category.images.build
  end

  def show
    @category = Category.find(params[:category_id])
    @image = Image.find(params[:id])

    @img = Magick::Image.read(@image.image.path).first
    @pix = @img.scale(1, 1)
    @avg_color = @pix.to_color(@pix.pixel_color(0,0))
  end

  def destroy
    @category = Category.find(params[:category_id])
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to @category
  end

  def create
    @category = Category.find(params[:category_id])
    @image = @category.images.build(image_params)
    if @image.save
      redirect_to @category
    else
      render :new
    end

  end

  private
  def image_params
    params.require(:image).permit(:title, :image)
  end
end

app/controllers/similar_images_controller.rb
class SimilarImagesController < ApplicationController
  def index
    redirect_to new_category_image_similar_image_path
  end

  def new
    @category = Category.find(params[:category_id])
    @image = Image.find(params[:image_id])
    @similar_image = @image.similar_images.build
  end

  def create
    @category = Category.find(params[:category_id])
    @image = Image.find(params[:image_id])
    @similar_image = @image.similar_images.build(similar_image_params)
    if @similar_image.save
      redirect_to category_image_path(@category, @image)
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:category_id])
    @image = Image.find(params[:image_id])
    @similar_image = SimilarImage.find(params[:id])

    @img = Magick::Image.read(@similar_image.image.path).first
    @pix = @img.scale(1, 1)
    @avg_color = @pix.to_color(@pix.pixel_color(0,0))
  end

  def destroy
    @category = Category.find(params[:category_id])
    @image = Image.find(params[:image_id])
    @similar_image = SimilarImage.find(params[:id])
    @similar_image.destroy
    redirect_to category_image_path(@category, @image)
  end

  private
  def similar_image_params
    params.require(:similar_image).permit(:title, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/similar_images_helper.rb
module SimilarImagesHelper
end

app/views/categories/index.html.erb
<div class="category-index__title title">All categories</div>

<% if @categories.any? %>
    <table class="category-index__table">
      <tr>
        <th>#</th>
        <th>Category name</th>
        <th>Amount of images</th>
      </tr>
      <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= link_to category.title, category_path(category) %></td>
        <td><%= category.images.count %></td>
      </tr>
      <% end %>

    </table>

<% end %>

app/views/categories/new.html.erb
<div class="title">New category</div>

<%= form_for (@category), html: {class: 'new_category-form new-form'} do |f| %>
  <div class="category-input input">
    <%= f.label :title, 'Title: ', class: 'category-input__title input__title' %>
    <%= f.text_field :title %>
  </div>
  <div class="">
    <%= f.submit 'Save', class: 'btn-save' %>
  </div>
<% end %>

<%= form_for [@category] do |f| %>
    <%= render 'shared/errors', object: @category %>
    <%# ... %>
<% end %>

app/views/categories/show.html.erb
<div class="title"><%= @category.title %></div>
<div class="links">
  <%= link_to "Delete category", category_path(@category), method: :delete, data: {confirm: "Are you sure?"} %>
  |
  <%= link_to "Add image", new_category_image_path(@category) %>
</div>
<hr class="links-hr">
<% @category.images.each do |img| %>
  <div class="image">
    <div class="image-title">
      <%= link_to img.title, category_image_path(@category, img)  %>
    </div>
    <div class="image-img">
      <%= image_tag img.image.url if img.image? %>
    </div>
  </div>

<% end %>

app/views/images/new.html.erb
<div class="title">New image</div>

<%= form_for([@category, @image], html: {class: 'new-form'}) do |f| %>
  <div class="input">
    <%= f.label :title, 'Title:', class: 'input__title' %>
    <%= f.text_field :title %>
  </div>
  <div class="file-upload">
    <label><%= f.file_field :image, id: 'file-input' %>Choose file</label>
    <div id="file-description">Image is not choosen</div>
  </div>
  <div class="">
    <%= f.submit 'Save', class: 'btn-save' %>
  </div>
<% end %>

<%= form_for [@category, @image] do |f| %>
    <%= render 'shared/errors', object: @image %>
    <%# ... %>
<% end %>

app/views/images/show.html.erb
<div class="links">
  <%= link_to 'Back', category_path(@category) %>
</div>
<div class="title">
  <%= @image.title %>
</div>
<div class="image-wrapper">
  <div class="image-show__img">
    <%= image_tag @image.image.url if @image.image? %>
  </div>
  <div class="image-show__info">
    <div class="image-show__info-text">
      Original size: <%= @image.image.width %> x <%= @image.image.height %>
    </div>
    <div class="image-show__info-text">
      Content type: <%= @image.image.content_type %>
    </div>
    <div class="image-show__info-text">
      Average color: <%= @avg_color %>
    </div>
    <div class="image__avg-color__square" style="background-color: <%= @avg_color %>">
    </div>
  </div>
</div>

<div class="links">
  <%= link_to "Delete image", category_image_path(@category, @image), method: :delete, data: {confirm: "Are you sure?"} %>
  |
  <%= link_to "Add similar image", new_category_image_similar_image_path(@category, @image) %>

</div>

<% if @image.similar_images.any? %>
  <div class="title similar-image__title">Similar images</div>
  <% @image.similar_images.each do |sml_img| %>
    <div class="similar-image">
      <div class="image-title">
        <%= link_to sml_img.title, category_image_similar_image_path(@category, @image, sml_img)  %>
      </div>
      <div class="image-img">
        <%= image_tag sml_img.image.url if sml_img.image? %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gallery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="content">
      <header>
        <div class="container">
          <div class="header__inner">
            <div class="logo">
              <%= link_to 'Gallery', root_path %>
            </div>
            <ul class="nav">
              <li class="nav-link all-categories-link"><%= link_to 'All categories', categories_path %></li>
              <li class="nav-link"><%= link_to 'New category', new_category_path %></li>
            </ul>
          </div>

        </div>
      </header>

      <div class="container">
        <%= yield %>
      </div>
    </div>

    <footer>
      <div class="container">
        <div class="footer-inner">
          <div class="footer-text">
            All rights reserved &copy;
          </div>
        </div>

      </div>
    </footer>

  </body>
</html>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script>
$(document).ready( function() {
    $("#file-input").change(function(){
         var filename = $(this).val().replace(/.*\\/, "");
         $("#file-description").html(filename);
    });
});
</script>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="errors">
    <div class="errors-title">The following errors were found:</div>
    <ul class="">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/similar_images/new.html.erb
<div class="title">New similar image</div>

<%= form_for([@category, @image, @similar_image], html: {class: 'new-form'}) do |f| %>
  <div class="input">
    <%= f.label :title, 'Title:', class: 'input__title' %>
    <%= f.text_field :title %>
  </div>
  <div class="file-upload">
    <label><%= f.file_field :image, id: 'file-input' %>Choose file</label>
    <div id="file-description">Image is not choosen</div>
  </div>
  <div class="">
    <%= f.submit 'Save', class: 'btn-save'%>
  </div>
<% end %>

<%= form_for [@category, @image, @similar_image] do |f| %>
    <%= render 'shared/errors', object: @similar_image %>
    <%# ... %>
<% end %>

app/views/similar_images/show.html.erb
<div class="links">
  <%= link_to 'Back', category_image_path(@category, @image) %>
</div>
<div class="title">
  <%= @similar_image.title %>
</div>
<div class="image-wrapper">
  <div class="image-show__img">
    <%= image_tag @similar_image.image.url if @similar_image.image? %>
  </div>
  <div class="image-show__info">
    <div class="image-show__info-text">
      Original size: <%= @similar_image.image.width %> x <%= @similar_image.image.height %>
    </div>
    <div class="image-show__info-text">
      Content type: <%= @similar_image.image.content_type %>
    </div>
    <div class="image-show__info-text">
      Average color: <%= @avg_color %>
    </div>
    <div class="image__avg-color__square" style="background-color: <%= @avg_color %>">
    </div>
  </div>
</div>

<div class="links">
  <%= link_to "Delete image", category_image_similar_image_path(@category, @image, @similar_image), method: :delete, data: {confirm: "Are you sure?"} %>
</div>